import type { Metadata } from "next";
import "./globals.css";
import { rubik } from "./fonts";

export const metadata: Metadata = {
  title: {
    template: '%s | IP Address Tracker',
    default: 'IP Address Tracker',
  },
  description: "IP Address Tracker - generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} ${rubik.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
